name: "budget-app"
services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgetdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - budget-net
  redis:
    image: redis:8
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - budget-net

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - budget-net

volumes:
  pgdata: null

networks:
  budget-net: null
