FROM node:22

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install 

COPY . .

RUN npx prisma generate && npm run build

EXPOSE 3000

ENV NODE_ENV=development

CMD ["npm", "start"]